### ISSUE TITLE
Add a "/event/{ID}/check_subscription" endpoint

### ISSUE THREAD

**Issue by AlexMog** [FightForSub/FFS-Api#22]
Add this endpoint to check automatically if the user has subscribed to the winner.

**Comment by AurelienFT** [comment]
Can I work on this ? We agree that the `ID` field is the `user_id` and not `event_id` ? This endpoint check for an user and not all users of an event ?

**Comment by AlexMog** [comment]
Nope, it's the EventID. The endpoint checks the current sub status of the user recognized by his token (same as this exemple: https://github.com/FightForSub/FFS-Api/blob/develop/src/main/java/tv/zerator/ffs/api/v1/resources/EventRegisterResource.java#L99)

**Comment by AlexMog** [comment]
But it's important to manage #23 first, and add a "ranking order" to the events. (to know who is the winner, ofc)

**Comment by AurelienFT** [comment]
Oh okey !
